# Generated by Django 6.0 on 2025-12-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('product_url', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=255)),
            ],
        ),
    ]
